import React from "react";
import OverviewSection from "./OverviewSection";
import SummaryBlock from "./SummaryBlock";
import GoldDivider from "../../ui/GoldDivider";
import GreyDivider from "../../ui/GreyDivider";
import {
  PhaseSection,
  PhaseContentBlock,
  PhaseImageWrapper,
  PhaseImage,
  PhaseTextContent,
  PhaseTitle,
  PhaseParagraph
} from "./SharedStyles";
import { PHASE_2_DATA } from "../developmentSectionData";

const Phase2Section: React.FC = () => {
  return (
    <>
      <OverviewSection
        title={PHASE_2_DATA.title}
        backgroundImage="https://images.unsplash.com/photo-1605146769289-440113cc3d00?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1920"
        breadcrumbLabel="Phase 2"
      />
      
      <PhaseSection>
        <SummaryBlock
          content={PHASE_2_DATA.overview}
          imageSrc="/assets/images/development/phase2/1.jpg"
          imageAlt="Phase 2 Overview"
          reverse={true}
        />

        <GoldDivider />

        <PhaseContentBlock>
          <PhaseImageWrapper>
            <PhaseImage 
              src="/assets/images/development/phase2/1.jpg" 
              alt="Development Objectives"
            />
          </PhaseImageWrapper>
          <PhaseTextContent>
            <PhaseTitle>Development Objectives</PhaseTitle>
            <PhaseParagraph>
              <strong>Workforce Demand:</strong> Provide attainable housing for the ~2,000+ workers generated by the industrial park, retail, and logistics facilities in Phase 1.
            </PhaseParagraph>
            <PhaseParagraph>
              <strong>Stabilize Land Value:</strong> Develop the residential component to elevate surrounding property values and attract complementary commercial services.
            </PhaseParagraph>
            <PhaseParagraph>
              <strong>Leverage QOZ Incentives:</strong> Tap into Qualified Opportunity Zone benefits to defer, reduce, or eliminate capital gains taxes on appreciation.
            </PhaseParagraph>
            <PhaseParagraph>
              <strong>Promote Community Integration:</strong> Incorporate walkable streets, community centers, green spaces, and easy connections to Phase 1's employment hubs.
            </PhaseParagraph>
          </PhaseTextContent>
        </PhaseContentBlock>

        <GreyDivider />

        <PhaseContentBlock $reverse>
          <PhaseImageWrapper $reverse>
            <PhaseImage 
              src="https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=800&q=80" 
              alt="Project Scope"
            />
          </PhaseImageWrapper>
          <PhaseTextContent $reverse>
            <PhaseTitle>Project Scope</PhaseTitle>
            <PhaseParagraph>
              <strong>Total Units:</strong> {PHASE_2_DATA.scope.totalUnits}
            </PhaseParagraph>
            <PhaseParagraph>
              <strong>Unit Types:</strong> {PHASE_2_DATA.scope.unitTypes.join(', ')}.
            </PhaseParagraph>
            <PhaseParagraph>
              <strong>Community Features:</strong> {PHASE_2_DATA.scope.communityFeatures.join(', ')}.
            </PhaseParagraph>
            <PhaseParagraph>
              <strong>Land Use:</strong> {PHASE_2_DATA.scope.landUse}
            </PhaseParagraph>
          </PhaseTextContent>
        </PhaseContentBlock>

        <GreyDivider />

        <PhaseContentBlock>
          <PhaseImageWrapper>
            <PhaseImage 
              src="https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80" 
              alt="Financing Structure"
            />
          </PhaseImageWrapper>
          <PhaseTextContent>
            <PhaseTitle>Financing Structure</PhaseTitle>
            <PhaseParagraph>
              <strong>Estimated Cost:</strong> {PHASE_2_DATA.financing.estimatedCost}
            </PhaseParagraph>
            <PhaseParagraph style={{ marginTop: '1rem' }}>
              <strong>Capital Sources:</strong>
            </PhaseParagraph>
            {PHASE_2_DATA.financing.sources.map((source, idx) => (
              <PhaseParagraph key={idx} dangerouslySetInnerHTML={{ __html: source }} />
            ))}
          </PhaseTextContent>
        </PhaseContentBlock>

        <GreyDivider />

        <PhaseContentBlock $reverse>
          <PhaseImageWrapper $reverse>
            <PhaseImage 
              src="https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80" 
              alt="Development Timeline"
            />
          </PhaseImageWrapper>
          <PhaseTextContent $reverse>
            <PhaseTitle>Development Timeline</PhaseTitle>
            {PHASE_2_DATA.timeline.map((phase, index) => (
              <PhaseParagraph key={index}>
                <strong>{phase.milestone} ({phase.targetDate}):</strong> {phase.keyActions}
              </PhaseParagraph>
            ))}
          </PhaseTextContent>
        </PhaseContentBlock>

        <GreyDivider />

        <PhaseContentBlock>
          <PhaseImageWrapper>
            <PhaseImage 
              src="https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80" 
              alt="Phase 1 & 2 Synergy"
            />
          </PhaseImageWrapper>
          <PhaseTextContent>
            <PhaseTitle>Phase 1 & 2 Synergy</PhaseTitle>
            {PHASE_2_DATA.synergy.map((item, idx) => (
              <PhaseParagraph key={idx} dangerouslySetInnerHTML={{ __html: item }} />
            ))}
          </PhaseTextContent>
        </PhaseContentBlock>
      </PhaseSection>
    </>
  );
};

export default Phase2Section;
