// Modular data for NewsSection

export interface NewsArticle {
  id: number;
  title: string;
  date: string;
  location: string;
  category: string;
  image: string;
  paragraphs: string[];
}

export const NEWS_ARTICLES: NewsArticle[] = [
  {
    id: 17,
    title: "APOZ was Introduced and Presented to a Global E-Bike Giant",
    date: "October 30, 2025",
    location: "Bradenton, Florida",
    category: "Company Update",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), ASC Global team met with the delegation from AIMA Technology Group led by its senior executive management team on October 28th in Sarasota, Florida.",
      "According to Mr. David Champ, the President & CEO of the company, AIMA E-Bike is a global leader in electric two-wheel mobility, specialized in stylish, high-performance e-bikes, e-scooters, and electric motorcycles, with annual sales exceeds $3 billion dollars worldwide (U.S., Europe and Southeast Asia).",
      "AIMA E-Bike already has its dealer network in the U.S. and is now seeking an ideal location for R & D and final assembly in the Sunbelt States area. After a detailed and thorough introduction of APOZ presented to the delegation, they are very impressed with the FTZ & QOZ dual-status tariff benefits and tax incentives of APOZ (Asia Pacific Opportunity Zone), and expressed strong interests to explore and discuss further with ASC Global Inc.",
      "AIMA is well known for its advanced technical innovations, such as Azure Controller: a proprietary smart energy system (re-Gen) that recaptures kinetic energy during braking or down hill riding to extend battery range, Hydraulic Disc Brakes and Superior Range (many models exceed 100 KM per charge with smart energy recovery systems and lithium ion battery system).",
      "For any further information, please contact Mr. David Champ at (631) 397-1111.",
    ],
  },
  {
    id: 16,
    title: "APOZ Team is Excited to Receive a Rare Earth Delegation from Asia",
    date: "October 17, 2025",
    location: "Houston, Texas",
    category: "Company Update",
    image: "https://images.unsplash.com/photo-1581092160562-40aa08e78837?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), is making an announcement today that a rare earth trade delegation from Asia is coming to visit APOZ next week.",
      "According to Mr. David Champ, the President & CEO of the company, a MOU of bilateral cooperation was executed with this rare earth company on June 8th this year, and an invitation was issued to this delegation shortly after.",
      "On August 1st, this delegation received visa approval from the U.S. General Consulate for coming to visit APOZ and conduct further discussion about setting up operation at APOZ in Texas. On the other hand, ASC Global Inc. has been exploring the feasibility of building a joint-venture entity in Vietnam for rare earth mining for many months already since late last year.",
      "The proposed operation at APOZ will be the final stage of Precipitation and Conversion (purified REFs are precipitated as oxalates/hydroxides, then calcined to form Rare Earth Oxides). These oxides will then be further reduced to metals using electrolysis and/or metallothermic reduction.",
      "David Champ further stated, this delegation will land and arrive in New York on the 20th of October, and then meet up with the APOZ management team shortly after.",
      "For any further information, please contact Mr. David Champ at (631) 397-1111.",
    ],
  },
  {
    id: 15,
    title: "The Largest House Boat Resort in the U.S. is Being Planned",
    date: "October 10, 2025",
    location: "Taipei, Taiwan",
    category: "Company Update",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), on October 7th, 2025 has started a J.V. discussion with American Software Capital (D/B/A American Softbank Capital) to co-develop the largest house boat resort project on Paradise Island, Florida.",
      "According to David Champ, President and CEO of the company, as ASC Global Inc. is working on an ADU Space Capsule Prefab home project at its APOZ (Asia Pacific Opportunity Zone) business park in Texas, and house boat just happens to be one of the ADU (accessory dwelling unit) products it offers, therefore it makes perfect business sense to utilize this house boat product on the Paradise Island project in Florida.",
      "These house boats will be operated as rental properties and operated by ASC Global Inc.",
      "For any further information, please contact Mr. David Champ at (631) 397-1111.",
    ],
  },
  {
    id: 14,
    title: "TKCM is Invited by Taiwan to Attend the Aerospace & UAV Summit",
    date: "October 8, 2025",
    location: "Bradenton, Florida",
    category: "Event",
    image: "https://images.unsplash.com/photo-1540962351504-03099e0a754b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), was invited by the Ministry of Economic Affairs of Taiwan (R.O.C.) to attend the Aerospace and UAV Summit to be held in Taipei on October 23rd, 2025.",
      "According to David Champ, President and CEO of the company, this very important summit will be held at the Sheraton Grand Hotel in Taipei on October 23rd. It is focused to promote the collaboration between U.S. and Taiwan in 'Non-Red Supply Chain' and to encourage the Taiwanese companies to set up their manufacturing operations in the U.S.",
      "APOZ as the only publicly recognized FTZ + QOZ dual-status Business Park (Foreign Trade Zone and Qualified Opportunity Zone) in the U.S. today, it is the most favorable and ideal location for these Taiwanese companies (including some of the U.S. domestic companies from other states) to establish their production and manufacturing operations.",
      "The FTZ + QOZ dual-status APOZ Business Park can provide tremendous savings on tariff and duties, along with the convenience for re-exporting to the global market and unprecedented savings on capital gain taxes, creating a true win-win strategic alliance relationship between the U.S. and Taiwan.",
      "The delegation from ASC Global Inc. will also visit some of the local companies in Taiwan who have already expressed interests in setting up operations at APOZ, and certain government officials whom have been supporting the APOZ project since its inception.",
      "For any further information, please contact Mr. David Champ at (631) 397-1111.",
    ],
  },
  {
    id: 13,
    title: "APOZ is Getting Ready for the Very First Space Capsule Home Production Center",
    date: "October 2, 2025",
    location: "Bradenton, Florida",
    category: "Company Update",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), is getting ready to start the very first Space Capsule Home production facility in the U.S.",
      "According to Mr. David Champ, President and CEO of the company: 'We're building a new generation of modular camp pods - blending aesthetics, functionality, and compliance into one intelligent unit. Each StarPod features modern and advanced smart control systems, hurricane-rated structure, and sustainable materials, backed by ASTM and Miami-Dade certifications for deployment in high-wind zones like Florida and Texas.'",
      "Whether for eco-resorts, glamping hotels, disaster relief, or public shelters, StarPod offers rapid deployment and scalable living - redefining how we inhabit the outdoors.",
      "The product line will consist of two main categories - 20 ft. model (160 sq.ft) and 40 ft. model (320 sq.ft), each comes with A/C, full bath, micro kitchen with refrigerator and comfortable living space. This facility will be the very first HUD certified manufacturing facility in the U.S. with ASTM and DBPR / IBCC certifications.",
      "These products will have vast market demands in many market segments, including ADU (Accessory Dwelling Unit), tiny home development, glamping site, scenic resorts, Airbnb and many more. The starting price will be around $9,499 and up to $29,499. The gross profit margin will be around 20%, and the annual production capacity will be around 20,000 units.",
      "For any further information, please contact Mr. David Champ at (631) 397-1111.",
    ],
  },
  {
    id: 12,
    title: "TKCM is Entering the 700 Billion Dollar Affordable Housing Market",
    date: "September 30, 2025",
    location: "Asian Pacific Industrial Park",
    category: "Company Update",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), is now gearing up to enter the 700 billion dollar affordable housing market in the U.S.",
      "According to David Champ, President and CEO of the company, affordable housing has been in huge demand throughout the U.S. in recent years (approximately 9 million units according to NLIHC), driven by a mix of economic pressures, demographics shifts, and policy uncertainty.",
      "After thorough research and studies, ASC Global Inc. has discovered the best approach to construct quality and durable affordable housing units is to utilize modern light-steel frame structure modular kits, made in a highly automated and robotic factory within APOZ (FTZ + QOZ dual-status) and then shipped to the job site for final assembly and completion.",
      "This business model can achieve: 1) Eliminate Material Waste - significantly save unnecessary material waste and unit cost by using precision laser cutting and welding equipment; 2) Foolproof SOP - monitored Standard Operating Procedures to improve production efficiency and eliminate human error and delay; 3) Reduced Labor Costs - greatly reduce production plant and construction-site labor costs in a controlled environment; 4) Discounted Material Costs - very favorable pricing achieved by large quantity material purchasing; 5) Better Time Management - saving valuable time on both permitting and construction, resulting in financial savings on both soft cost and hard cost.",
      "Eric Fang, Co-Founder of the APOZ project further states, the company is teaming up with the largest light steel modular home manufacturer in Asia to build a 200,000 sq.ft. facility at APOZ in 2026. The production capacity will be 50,000 units for the first year, and the projected sales price will be around $80,000 per unit ($4,000,000,000 in projected annual sales revenue, and $750,000,000 in projected annual gross profit). We will sell the finished & completed units for under $200,000 in Texas and Florida, and will sell the Home Kits to other builders through a distributorship network in other states.",
      "For any further information, please contact Mr. David Champ at (631) 397-1111.",
    ],
  },
  {
    id: 11,
    title: "ASC Global is Moving Forward on Paradise Island Project",
    date: "September 19, 2025",
    location: "Bradenton, Florida",
    category: "Company Update",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), is announcing the completion of the architectural design of Paradise Island's Phase One development project.",
      "According to David Champ, President and CEO of the company, ASC Global Inc. executed a L.O.I. with American Software Capital (ASC) in October 2024 to acquire the Paradise Island Project in Florida. It is a 165 acres premium development site, consisted by a peninsula, two larger islands and several smaller islands.",
      "Paradise Island is located on Peace River, Arcadia, Desoto County, north of Charlotte Harbor and Gulf of America (South of Sarasota and North of Naples).",
      "The proposed Phase One development is located on the Peninsula part right off Sunny Breeze Road and Paradise Golf Course. It will have 180 units of high-end steel-structure waterfront town houses, restaurant, retail space, marina, community pool, scenic pond and others on 22 acres of the peninsula portion.",
      "A co-development plan is now being discussed between American Software Capital and ASC Global Inc.",
      "For further information or assistance, please contact the company at (631) 397-1111.",
    ],
  },
  {
    id: 9,
    title: "Second Online Summit of APOZ was Held",
    date: "September 15, 2025",
    location: "Asian Pacific Industrial Park",
    category: "Event",
    image: "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), held another successful online summit on Zoom for its APOZ (Asia Pacific Opportunity Zone) project on September 5th.",
      "As per Mr. David Champ, President & CEO of Token Communities and Founder of APOZ, now more and more people are realizing this rare and unique FTZ + QOZ dual-status master planned development project is the answer to the present tariff war era as it can create an ideal and harmonious solution to U.S. economic growth and overseas manufacturers.",
      "The Foreign Trade Zone benefits can reduce the tariff burdens for manufacturers by setting up their final-assembly plants at APOZ, in addition to the capital gain tax savings under the Qualified Opportunity Zone (OBBBA) Act. APOZ will attract dozens of international manufacturers to invest and set up their operations, creating hundreds of new local job opportunities, generating new tax revenue and bringing prosperity into the area - a true win-win solution.",
      "The online summit was hosted by ASC Global Inc., APOZ Steering Committee, and participated by Skytower Group Inc., Sinoaccess Group, HTL Certified Public Accountants, Yingke Law Firm, NI, WANG & MASSAND, PLLC, TransGlobal Financial, George H.W. Bush Foundation for U.S.-China Relations, and The Carter Center's U.S.-China Program.",
      "The seminar brought together experts and executives from the fields of industry, capital markets, taxation, legal compliance, and cross-border investment to explore how Chinese and Asian companies can seize global expansion opportunities amid supply chain restructuring, trade policy shifts, and emerging market trends.",
      "The seminar highlighted APOZ as a strategic gateway for Asian manufacturing companies entering the U.S. market, leveraging the dual status and policy advantages of Qualified Opportunity Zones (QOZ) and Foreign Trade Zone (FTZ-171), providing comprehensive support from local manufacturing and supply chain integration to tax optimization and investment exit strategies.",
    ],
  },
  {
    id: 10,
    title: "New Waterfront Homes are Ready for Sale",
    date: "July 11, 2025",
    location: "Bradenton, Florida",
    category: "Company Update",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), a luxury waterfront real estate development company in Florida, is pleased to announce multiple new waterfront luxury homes are getting ready to be listed with its local Coldwell Bankers realtors.",
      "According to Mr. David Champ, the President & CEO of the company, the first group of new construction homes located in Northport (Sarasota County) and Port Charlotte (Charlotte County) are gradually being completed at the moment.",
      "These new homes are all canal-front luxury single family homes with 4 bedrooms, 1 flex room (can be used as the 5th bedroom), 2.5 car garage, large play room and sun deck balcony on the second floor with great view of the boat dock and canal. All these new homes are within just one block away from the open water, with direct access to the Gulf of America.",
      "This model is called 'Summit', approximately 3,600 sq.ft of interior space, sitting on 10,000 - 20,000 sq.ft of land. The proposed sales price for these new construction homes are currently ranged from $1,350,000 to $1,900,000 as the listing prices.",
      "The company is now an OTC-ID listed company starting July 1st this year, and the management has been working aggressively on the APOZ (Asia Pacific Opportunity Zone) project in Chambers County, Texas. Another DRC (Development Review) web meeting took place this morning with all the related county agencies and departments, a detailed Master Planned Development architectural design plan is now being prepared for the final review and approval.",
      "For any further information or assistance, please call David at (631) 397-1111.",
    ],
  },
  {
    id: 8,
    title: "APOZ is Gaining Momentum Fast on the Global Stage",
    date: "August 13, 2025",
    location: "Houston, Texas",
    category: "Press Release",
    image: "https://images.unsplash.com/photo-1581094271901-8022df4466f9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), has reached an agreement with a major hydraulic valves manufacturer to set up their final assembly plant at APOZ (Asia Pacific Opportunity Zone) in Chambers County, Texas.",
      "According to Mr. David Champ, the President & CEO of the company, the CEO of Bundor Valves visited the APOZ job site earlier this year, and performed a very thorough due diligence of the investment environment of APOZ and the market of Texas. He is very pleased with the strategic location, and the benefits of FTZ + QOZ (Free Trade Zone + Qualified Opportunity Zone) combined, which can significantly maximize the operating performance and the bottom line profit of his company.",
      "Dr. Eric Fang, Co-Founder of the APOZ project further added, as Houston is the petrochemical capital in the U.S., therefore it is a great market for hydraulic valves products. APOZ is centrally located between the Pacific Coast and Atlantic Coast, adjacent to Port of Houston (ranked #1 in foreign waterborne tonnage), sitting right on the energy corridor (Interstate 10). APOZ is the most ideal location for Bundor Valves to set up their North America operation.",
      "Ms. Tina Pei Wise, Director of Coordination further commented, Bundor Valves will be a great asset to APOZ and create over 100 new local jobs in the beginning to start its operation at APOZ, and generate about 75 million dollars in annual sales revenue once it fulfills its Phase One production plan.",
      "For any further information, please contact Mr. David Champ at (631) 397-1111.",
    ],
  },
  {
    id: 7,
    title: "APOZ Is Now Receiving Interests From Both Domestic and International",
    date: "August 11, 2025",
    location: "Asian Pacific Industrial Park",
    category: "Press Release",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), recently has received a great deal of interests and inquiries from many domestic companies in the U.S.",
      "According to Mr. David Champ, the President & CEO of the company, as the APOZ (Asia Pacific Opportunity Zone) project is moving forward steadily over the past few months, this unique FTZ + QOZ Business Park concept is quickly gaining name recognition from the business communities around the globe.",
      "Not just from the foreign companies in the Asian countries as in the beginning, now more and more U.S. domestic companies are interested in relocating their manufacturing operations to our APOZ Business Park, as they can also benefit greatly from the FTZ + QOZ dual-status advantages.",
      "Some of these companies are publicly-traded companies (Pubco), and they can also significantly reduce their operating costs and improve their bottom-line profit by moving their companies into the APOZ Business Park.",
      "As per Tina Pei Wise who is the Director of Coordination of the Company, the growth potential and value of APOZ is now noticed by international capital circles, the company is now having dialogues with multiple hedge funds and institutions about collaborations.",
      "For any further information, please contact Mr. David Champ at (631) 397-1111.",
    ],
  },
  {
    id: 6,
    title: "The Very First Solar Powered Community in the U.S.",
    date: "July 22, 2025",
    location: "Asian Pacific Industrial Park",
    category: "Press Release",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), is now gearing up to build its APOZ Project (Asia Pacific Opportunity Zone) to become the very first solar town in the U.S.",
      "According to Mr. David Champ, the President & CEO of the company, the Greater Houston Area is one of the most ideal areas in the U.S. to create a solar city. It has over 2,600 hours of qualified solar condition annually, and the State of Texas has many incentive programs available, such as ITC (Federal Solar Investment Tax Credit), Property Tax Exemption, Local Utility Rebates and Solar Buy Back Plans.",
      "The Company is in discussion with one of the largest solar panel manufacturers in the world now, to turn its APOZ Project (industrial buildings, commercial buildings and residential buildings) into a huge solar farm power plant. Based upon preliminary due diligence, APOZ can generate about 57.5 MW annually (0.25 MW / acre), and results in about $5.66 million per year in revenue.",
      "Additional revenue streams will include Renewable Energy Credits (RECs), Community Solar or Retail Sales and others.",
      "David Champ further added, a Solar & Clean Energy Sub-Zone is being planned at the moment to attract some of the related industries to move in and set up productions at APOZ, including solar panel production, power storage products production, lithium-ion battery production and others.",
      "Several other sub-zones are also being planned as well, such as Food Production Sub-Zone, Electric Vehicle Production Sub-Zone, General Merchandise Production Sub-Zone and others.",
      "For any further information, please contact Mr. David Champ at (631) 397-1111.",
    ],
  },
  {
    id: 5,
    title: "Another Conference of APOZ was Held in New York",
    date: "July 21, 2025",
    location: "New York City, New York",
    category: "Event",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), held another conference at the Sheraton Four Point Hotel on July 19th in New York.",
      "According to Mr. David Champ, the President & CEO of the company, nearly 100 interested investors attended this event, including local real estate developers, business owners and friends from the media.",
      "The most recent and updated progress status was presented at this conference; it further strengthens the project concept and name recognition within the Asia American community in the Greater New York area.",
      "Many attendees have expressed strong interests in investing in the APOZ (Asia Pacific Opportunity Zone) project which is the only FTZ (Foreign Trade Zone) + QOZ (Qualified Opportunity Zone) dual-status business park in the U.S. designed to attract hundreds of manufacturers to set up their production operation there and save a ton of money in upfront tariff expenses, and also save a lot of money on the capital gain tax.",
      "Added by Mr. Jacky Xie who is the President of ACUA (American Chinese United Association) also a co-founder of the APOZ project, this event was a great success and generated many interests and inquiries from the attendees.",
      "For any further information, please contact Mr. David Champ at (631) 397-1111.",
    ],
  },
  {
    id: 4,
    title: "LOBO EV Made Announcement to Enter APOZ",
    date: "July 17, 2025",
    location: "Asian Pacific Industrial Park",
    category: "Press Release",
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=1080",
    paragraphs: [
      "ASC Global Inc., a wholly-owned subsidiary of Token Communities (OTC: TKCM), has executed an agreement with LOBO EV (a Nasdaq company) to develop a strategic cooperation relationship to set up a production facility at APOZ (Asia Pacific Opportunity Zone) to manufacture various types of electric vehicles, including electric scooters, electric bikes, electric golf carts and others.",
      "According to Mr. David Champ, the President & CEO of the company, LOBO EV is a very reputable EV products manufacturer, and it has been growing steadily over the past years with excellent growth potential in the North America market.",
      "With the help and assistance to be provided by ASC Global Inc. and the excellent strategic location and benefits (QOZ + FTZ dual status) of APOZ Business Park, LOBO EV can easily reach their growth target and maximize their market potentials.",
      "As per Ms. Ruby Lin, Director of Business Development, APOZ has been receiving excellent inquiries and responses from dozens of companies from various manufacturers in Taiwan and other Asia Pacific countries. These companies are in UAV (drones), solar panels, sport goods, electric vehicles, food & beverages, building materials and many others.",
      "For any information about APOZ, please contact David at (631) 397-1111.",
    ],
  },
  {
    id: 1,
    title: "Momentum Builds for APOZ: Groundbreaking Set for Fall 2025 Amid Global Investor Interest",
    date: "June 4, 2025",
    location: "Asian Pacific Industrial Park",
    category: "Press Release",
    image: "https://images.unsplash.com/photo-1613928270169-4e4462c75a79?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbmR1c3RyaWFsJTIwZGV2ZWxvcG1lbnQlMjBjb25zdHJ1Y3Rpb258ZW58MXx8fHwxNzY0NjU4ODA4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    paragraphs: [
      "As global awareness of the Asia Pacific Opportunity Zone (APOZ) grows, Token Communities Ltd. (OTC: TKCM) and its subsidiary ASC Global Inc. are preparing for the next major milestone — the official groundbreaking ceremony, scheduled for September 2025 in Greater Houston.",
      "Following successful presentations at the International Trade Center in Houston and the first overseas APOZ conference in Shanghai, interest from both domestic and international investors has surged.",
      "Developers, fund managers, and institutional investors from the U.S., China, Singapore, and beyond are engaging with the APOZ team to explore participation in residential, commercial, and industrial phases of the master-planned project.",
      "David Champ, CEO of Token Communities Ltd., noted: 'What started as a bold vision is rapidly becoming reality. The interest we've received — especially from Asia-Pacific partners — shows that APOZ is positioned to become a global hub for opportunity, investment, and innovation.'",
      "The APOZ site plan includes affordable housing starting at $188,000, logistics and business zones, and green innovation spaces.",
      "With support from local government agencies and international stakeholders, the project is moving swiftly through final planning stages.",
      "Stay tuned for more announcements about investor tours, groundbreaking details, and upcoming events in Taiwan and Singapore.",
      "For partnership and investment inquiries, please contact: info@apoz.us",
    ],
  },
  {
    id: 2,
    title: "APOZ Project Unveiled at ITC Conference: Affordable Housing and Economic Growth in Houston",
    date: "May 24, 2025",
    location: "Asian Pacific Industrial Park",
    category: "Event",
    image: "https://images.unsplash.com/photo-1758520144427-ddb02ac74e9d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxleGVjdXRpdmUlMjBoYW5kc2hha2UlMjBidXNpbmVzc3xlbnwxfHx8fDE3NjQ2NTg4MDh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    paragraphs: [
      "On May 23, 2025, Token Communities Ltd. (OTC PINK: TKCM), through its subsidiary ASC Global Inc., presented the Asia Pacific Opportunity Zone (APOZ) Project at the International Trade Center (ITC) Board of Directors Inauguration Ceremony in Houston.",
      "The APOZ Project is a master-planned community set to commence construction in Q4 2025.",
      "It will feature an industrial park, business center, commercial section, and residential subdivisions.",
      "Notably, the development aims to offer high-quality, modern single-family homes starting at $188,000 for three-bedroom units, with multi-family homes also in the planning stages.",
      "The initiative addresses the significant demand for affordable housing in the Greater Houston area.",
      "ASC Global Inc. is committed to collaborating with the City of Houston and the ITC to meet this growing need.",
    ],
  },
  {
    id: 3,
    title: "Token Communities Ltd. Hosts First Overseas APOZ Conference in Shanghai",
    date: "May 20, 2025",
    location: "Asian Pacific Industrial Park",
    category: "Event",
    image: "https://images.unsplash.com/photo-1505624198937-c704aff72608?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3Jwb3JhdGUlMjBtZWV0aW5nJTIwcm9vbXxlbnwxfHx8fDE3NjQ2NTg4MTN8MA&ixlib=rb-4.1.0&q=80&w=1080",
    paragraphs: [
      "On May 20, 2025, Token Communities Ltd. (OTC: TKCM), through its subsidiary ASC Global Inc., hosted its inaugural overseas APOZ conference at the Westin Bund Center in Shanghai.",
      "The event aimed to introduce the APOZ initiative to the Asia Pacific business community, highlighting investment opportunities and fostering regional engagement.",
      "CEO David Champ announced plans for additional conferences in Taiwan, Singapore, and other Asian cities, citing significant interest from the region.",
      "These events are part of the company's strategy to expand the APOZ initiative within the Asia Pacific markets.",
      "Project director Leo Lei indicated that final site-plan modifications are underway with assistance from local government agencies.",
      "A groundbreaking ceremony is anticipated for September 2025, marking a significant milestone in the project's development and implementation.",
    ],
  },
];
